//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPDetailsWebApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPJob
    {
        public string Id { get; set; }
        public System.DateTime StartedOn { get; set; }
        public Nullable<System.DateTime> FinishedOn { get; set; }
        public int Status { get; set; }
        public int Progress { get; set; }
        public int Total { get; set; }
    }
}
